import type { PageRecord, SitemapperResult } from '../types.js';

export function renderHtml(result: SitemapperResult): string {
  const payload = JSON.stringify(result).replace(/</g, '\\u003c');
  const siteHost = new URL(result.site).hostname;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Site index for ${escapeHtml(siteHost)}</title>
  <meta name="description" content="Public searchable site index and SEO health report generated by Sitemapper." />
  <style>${styles()}</style>
</head>
<body>
  <main class="shell">
    <header class="hero">
      <p class="eyebrow">Sitemapper public index</p>
      <h1>${escapeHtml(siteHost)}</h1>
      <p class="lede">A searchable public index generated from the site sitemap, with basic SEO and crawlability checks.</p>
      <div class="stats">
        ${statCard('Pages', result.stats.pages)}
        ${statCard('Sections', result.stats.sections)}
        ${statCard('Errors', result.stats.errors)}
        ${statCard('Warnings', result.stats.warnings)}
      </div>
      <div class="scores">
        ${scorePill('Index', result.scores.index)}
        ${scorePill('SEO', result.scores.seo)}
        ${scorePill('Sitemap', result.scores.sitemap)}
      </div>
    </header>

    <section class="panel controls">
      <input id="search" type="search" placeholder="Search titles, URLs, sections, descriptions..." autocomplete="off" />
      <select id="sectionFilter" aria-label="Filter by section">
        <option value="">All sections</option>
      </select>
      <select id="issueFilter" aria-label="Filter by issue severity">
        <option value="">All pages</option>
        <option value="error">Errors</option>
        <option value="warning">Warnings</option>
        <option value="notice">Notices</option>
        <option value="clean">Clean</option>
      </select>
    </section>

    <section class="grid two">
      <article class="panel">
        <h2>Recently updated</h2>
        <div id="recentList" class="stack"></div>
      </article>
      <article class="panel">
        <h2>Top sections</h2>
        <div id="sectionList" class="stack"></div>
      </article>
    </section>

    <section class="panel">
      <div class="tableHeader">
        <h2>All pages</h2>
        <p><span id="visibleCount"></span> shown</p>
      </div>
      <div class="tableWrap">
        <table>
          <thead>
            <tr>
              <th>Page</th>
              <th>Section</th>
              <th>Status</th>
              <th>Lastmod</th>
              <th>Issues</th>
              <th></th>
            </tr>
          </thead>
          <tbody id="pageRows"></tbody>
        </table>
      </div>
    </section>

    <section class="panel sources">
      <h2>Sources</h2>
      <p>Generated at ${escapeHtml(result.generatedAt)}.</p>
      <p>Robots: <a href="${escapeAttr(result.source.robotsUrl)}">${escapeHtml(result.source.robotsUrl)}</a></p>
      <p>Sitemaps:</p>
      <ul>${result.source.sitemapUrls.map((url) => `<li><a href="${escapeAttr(url)}">${escapeHtml(url)}</a></li>`).join('')}</ul>
      <p class="small">Sitemapper makes your sitemap useful to humans, not just crawlers.</p>
    </section>
  </main>

  <script id="sitemapper-data" type="application/json">${payload}</script>
  <script>${clientScript()}</script>
</body>
</html>`;
}

function statCard(label: string, value: number): string {
  return `<div class="stat"><span>${escapeHtml(label)}</span><strong>${value}</strong></div>`;
}

function scorePill(label: string, value: number): string {
  const tone = value >= 85 ? 'good' : value >= 65 ? 'warn' : 'bad';
  return `<div class="score ${tone}"><span>${escapeHtml(label)}</span><strong>${value}/100</strong></div>`;
}

function styles(): string {
  return `
:root { color-scheme: dark; --bg:#081018; --panel:#101923; --muted:#8ea0b4; --text:#eef5ff; --line:#223244; --soft:#152232; --good:#7ee787; --warn:#f2cc60; --bad:#ff7b72; --accent:#80bfff; }
* { box-sizing: border-box; }
body { margin:0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: radial-gradient(circle at top left, #17324d, var(--bg) 34rem); color:var(--text); }
a { color:var(--accent); }
.shell { width:min(1180px, calc(100% - 32px)); margin:0 auto; padding:48px 0; }
.hero { padding:36px; border:1px solid var(--line); border-radius:28px; background:linear-gradient(135deg, rgba(128,191,255,.14), rgba(16,25,35,.9)); box-shadow:0 24px 80px rgba(0,0,0,.35); }
.eyebrow { color:var(--accent); text-transform:uppercase; letter-spacing:.16em; font-size:12px; font-weight:800; margin:0 0 12px; }
h1 { font-size:clamp(42px, 8vw, 92px); line-height:.92; margin:0; }
h2 { margin:0 0 16px; font-size:20px; }
.lede { color:var(--muted); font-size:18px; max-width:780px; line-height:1.55; }
.stats, .scores { display:flex; flex-wrap:wrap; gap:12px; margin-top:22px; }
.stat, .score { border:1px solid var(--line); background:rgba(8,16,24,.55); border-radius:18px; padding:14px 16px; min-width:130px; }
.stat span, .score span { display:block; color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.08em; }
.stat strong, .score strong { display:block; margin-top:4px; font-size:24px; }
.score.good strong { color:var(--good); } .score.warn strong { color:var(--warn); } .score.bad strong { color:var(--bad); }
.panel { border:1px solid var(--line); background:rgba(16,25,35,.92); border-radius:24px; padding:22px; margin-top:18px; }
.controls { display:grid; grid-template-columns:1fr 220px 180px; gap:12px; }
input, select { width:100%; border:1px solid var(--line); background:var(--soft); color:var(--text); border-radius:14px; padding:13px 14px; font-size:15px; }
.grid.two { display:grid; grid-template-columns:1fr 1fr; gap:18px; }
.stack { display:grid; gap:10px; }
.item { border:1px solid var(--line); background:rgba(8,16,24,.38); border-radius:16px; padding:12px; }
.item strong { display:block; margin-bottom:4px; }
.item span, .small { color:var(--muted); font-size:13px; }
.tableHeader { display:flex; align-items:center; justify-content:space-between; gap:16px; }
.tableHeader p { color:var(--muted); margin:0; }
.tableWrap { overflow:auto; }
table { width:100%; border-collapse:collapse; min-width:880px; }
th, td { text-align:left; border-bottom:1px solid var(--line); padding:13px 10px; vertical-align:top; }
th { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.08em; }
td .title { font-weight:750; } td .url { color:var(--muted); font-size:13px; margin-top:4px; word-break:break-all; }
.badge { display:inline-flex; border:1px solid var(--line); border-radius:999px; padding:4px 8px; font-size:12px; margin:2px; color:var(--muted); }
.badge.error { color:var(--bad); border-color:rgba(255,123,114,.5); } .badge.warning { color:var(--warn); border-color:rgba(242,204,96,.5); } .badge.notice { color:var(--accent); border-color:rgba(128,191,255,.45); }
.actions { display:flex; gap:8px; }
button, .button { border:1px solid var(--line); background:var(--soft); color:var(--text); padding:8px 10px; border-radius:12px; text-decoration:none; cursor:pointer; }
.sources ul { margin-top:8px; }
@media (max-width: 800px) { .controls, .grid.two { grid-template-columns:1fr; } .hero { padding:24px; } }
`;
}

function clientScript(): string {
  return `
const data = JSON.parse(document.getElementById('sitemapper-data').textContent);
const pages = data.pages;
const search = document.getElementById('search');
const sectionFilter = document.getElementById('sectionFilter');
const issueFilter = document.getElementById('issueFilter');
const rows = document.getElementById('pageRows');
const visibleCount = document.getElementById('visibleCount');

const sections = [...new Set(pages.map(p => p.section))].sort();
for (const section of sections) {
  const option = document.createElement('option');
  option.value = section;
  option.textContent = section;
  sectionFilter.appendChild(option);
}

function severityCounts(page) {
  return page.issues.reduce((acc, issue) => {
    acc[issue.severity] = (acc[issue.severity] || 0) + 1;
    return acc;
  }, {});
}

function issueBadges(page) {
  if (!page.issues.length) return '<span class="badge">clean</span>';
  return page.issues.slice(0, 4).map(issue => '<span class="badge ' + issue.severity + '">' + issue.code + '</span>').join('') + (page.issues.length > 4 ? '<span class="badge">+' + (page.issues.length - 4) + '</span>' : '');
}

function matchesIssue(page, filter) {
  if (!filter) return true;
  if (filter === 'clean') return page.issues.length === 0;
  return page.issues.some(issue => issue.severity === filter);
}

function render() {
  const q = search.value.trim().toLowerCase();
  const sec = sectionFilter.value;
  const issue = issueFilter.value;
  const filtered = pages.filter(page => {
    const haystack = [page.title, page.url, page.path, page.section, page.description].filter(Boolean).join(' ').toLowerCase();
    return (!q || haystack.includes(q)) && (!sec || page.section === sec) && matchesIssue(page, issue);
  });

  visibleCount.textContent = String(filtered.length);
  rows.innerHTML = filtered.map(page => {
    return '<tr>' +
      '<td><div class="title">' + escapeHtml(page.title || '(missing title)') + '</div><div class="url">' + escapeHtml(page.path) + '</div></td>' +
      '<td>' + escapeHtml(page.section) + '</td>' +
      '<td>' + (page.status || '—') + '</td>' +
      '<td>' + escapeHtml(page.lastmod || '—') + '</td>' +
      '<td>' + issueBadges(page) + '</td>' +
      '<td><div class="actions"><a class="button" href="' + page.url + '">Open</a><button data-copy="' + page.url + '">Copy</button></div></td>' +
      '</tr>';
  }).join('');
}

function renderRecent() {
  const recent = [...pages].filter(p => p.lastmod).sort((a, b) => String(b.lastmod).localeCompare(String(a.lastmod))).slice(0, 8);
  document.getElementById('recentList').innerHTML = recent.map(page => '<div class="item"><strong>' + escapeHtml(page.title || page.path) + '</strong><span>' + escapeHtml(page.lastmod) + ' · ' + escapeHtml(page.path) + '</span></div>').join('') || '<p class="small">No lastmod values found.</p>';
}

function renderSections() {
  const counts = new Map();
  for (const page of pages) counts.set(page.section, (counts.get(page.section) || 0) + 1);
  const top = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10);
  document.getElementById('sectionList').innerHTML = top.map(([section, count]) => '<div class="item"><strong>' + escapeHtml(section) + '</strong><span>' + count + ' pages</span></div>').join('');
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
}

document.addEventListener('click', event => {
  const button = event.target.closest('button[data-copy]');
  if (!button) return;
  navigator.clipboard?.writeText(button.dataset.copy);
  button.textContent = 'Copied';
  setTimeout(() => { button.textContent = 'Copy'; }, 900);
});

search.addEventListener('input', render);
sectionFilter.addEventListener('change', render);
issueFilter.addEventListener('change', render);
renderRecent();
renderSections();
render();
`;
}

function escapeHtml(value: unknown): string {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] ?? char));
}

function escapeAttr(value: unknown): string {
  return escapeHtml(value);
}
